"""Add column quantity on purchase orders items

Revision ID: 454a84153241
Revises: fdb1063f194a
Create Date: 2023-07-04 00:47:28.650220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454a84153241'
down_revision = 'fdb1063f194a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
